# travis-ci.org build & test configuration
language: python
virtualenv:
    system_site_packages: true
python:
  - "2.7"
  #- "3.2"
env:
  #- ROOT=5-32-00
  #- ROOT=5-32-01
  #- ROOT=5-32-02
  #- ROOT=5-32-03
  - ROOT=5-32-04
  #- ROOT=5-33-02
  #- ROOT=5-33-02b
  #- ROOT=5-34-00
  #- ROOT=5-34-04
  #- ROOT=5-34-05
  #- ROOT=5-34-06
  #- ROOT=5-34-07
  - ROOT=5-34-08
  - ROOT=6-02-04
install: source ci/install.sh
script: bash ci/test.sh
cache: 
	apt
	directories: # also works for files ;)
  		- root_v5-34-25_python_2.7.tar.gz
  		- root_v6-02-04_python_2.7.tar.gz
